### ISSUE TITLE
Remove Marquee element

### ISSUE THREAD

**Issue by winniebosy** [opensource254/covid-19-web#155]
**Describe the bug**

- Marquee element is present in the app. 
- The presence of the element can trigger seizures and cause distractions for users with cognitive disabilities.
- Moving text can be difficult to read for people with low vision and people with reading and learning disabilities.
- UI control that moves can be difficult to activate, especially for people with limited dexterity.

**To Reproduce**
1. Go to inspect
2. Click on inspect (Q) to inspect the element.
4. See error.

**Expected behavior**
A clear and concise description of what you expected to happen
- Text will stop moving horizontally

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - Device: RedMi
 - OS: Andriod
 - Browser : firefox

**Additional context**

**Comment by StanleyMasinde** [comment]
Thank you @winniebosy for pointing out the accessibility issue.

I'll work on it.
